[package]
name = "namemap"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
regex = "1.10.6"
ron = "0.8.1"
serde = { version = "1.0.209", features = ["derive"] }
slotmap = { version = "1.0.7", features = ["serde"] }
